import { useRef, useState } from "react";
import { extractPdfText } from "../utils/pdf.js";
import { generateQuizFromText } from "../utils/quizGen.js";
import { generateQuizWithOpenAI, hasApiKey, OpenAIError } from "../utils/openai.js";
import { getMaterials, removeMaterial, saveMaterial } from "../utils/storage.js";
import { Link, navigate } from "../utils/router.js";

export default function FacultyUpload({ user }) {
  const [busy, setBusy] = useState(false);
  const [busyLabel, setBusyLabel] = useState("");
  const [error, setError] = useState("");
  const [extracted, setExtracted] = useState("");
  const [draft, setDraft] = useState(null);
  const [draftSource, setDraftSource] = useState(null); // "ai" | "local"
  const [title, setTitle] = useState("");
  const [list, setList] = useState(getMaterials());
  const [useAI, setUseAI] = useState(hasApiKey());
  const [count, setCount] = useState(8);
  const inputRef = useRef(null);
  const [dragOver, setDragOver] = useState(false);

  const handle = async (file) => {
    setError(""); setExtracted(""); setDraft(null); setDraftSource(null);
    if (!file) return;
    if (file.type !== "application/pdf" && !file.name.toLowerCase().endsWith(".pdf")) {
      setError("Please upload a .pdf file."); return;
    }
    setTitle(file.name.replace(/\.pdf$/i, ""));
    setBusy(true);
    try {
      setBusyLabel("Extracting text from PDF…");
      const text = await extractPdfText(file);
      setExtracted(text.slice(0, 8000));

      let questions = [];
      let source = "local";
      if (useAI && hasApiKey()) {
        try {
          setBusyLabel(`Asking gpt-4o-mini for ${count} questions…`);
          questions = await generateQuizWithOpenAI(text, { count });
          source = "ai";
        } catch (e) {
          const m = e instanceof OpenAIError
            ? (e.type === "auth"       ? "OpenAI rejected the key (401). Update it in Settings."
             : e.type === "rate_limit" ? "OpenAI rate limit — try again shortly."
             : e.message)
            : "Unexpected OpenAI error.";
          setError(`${m} Falling back to the offline heuristic.`);
        }
      }
      if (!questions.length) {
        setBusyLabel("Generating questions locally…");
        questions = generateQuizFromText(text, { maxQuestions: count });
        source = "local";
      }
      if (!questions.length) {
        setError("Could not extract enough text to generate a quiz. Try a text-based PDF.");
      }
      setDraft(questions);
      setDraftSource(source);
    } catch (e) {
      setError("Failed to read PDF: " + (e?.message || e));
    } finally {
      setBusy(false);
      setBusyLabel("");
    }
  };

  const save = () => {
    if (!draft?.length) return;
    saveMaterial({
      title: title.trim() || "Untitled material",
      by: user.name || user.email,
      when: new Date().toISOString(),
      summary: extracted.slice(0, 400),
      generatedQuiz: draft,
      source: draftSource
    });
    setList(getMaterials());
    setDraft(null); setExtracted(""); setTitle(""); setDraftSource(null);
    if (inputRef.current) inputRef.current.value = "";
  };

  const remove = (id) => { removeMaterial(id); setList(getMaterials()); };

  return (
    <section className="container section">
      <div className="spread mb-16">
        <div>
          <h2 className="section__title">Upload PDF &amp; auto-generate quiz</h2>
          <p className="section__sub">
            Upload a text-based PDF (lecture notes, chapter). Text is extracted in the browser using pdf.js,
            then questions are generated by{" "}
            <b>{hasApiKey() && useAI ? "OpenAI gpt-4o-mini" : "the offline heuristic"}</b>.
          </p>
        </div>
        <div className="row" style={{ gap: 10, flexWrap: "wrap" }}>
          <label className="row" style={{ gap: 6, fontSize: 13 }}>
            <input
              type="checkbox"
              checked={useAI}
              disabled={!hasApiKey()}
              onChange={(e) => setUseAI(e.target.checked)}
            />
            Use OpenAI {hasApiKey() ? "" : "(add key in Settings)"}
          </label>
          <label className="row" style={{ gap: 6, fontSize: 13 }}>
            Questions:
            <select
              value={count}
              onChange={(e) => setCount(Number(e.target.value))}
              style={{ background: "var(--bg-2)", color: "var(--text)", padding: "6px 8px", borderRadius: 8, border: "1px solid var(--border)" }}
            >
              {[5, 8, 10, 15, 20].map(n => <option key={n} value={n}>{n}</option>)}
            </select>
          </label>
          {!hasApiKey() && (
            <Link to="/settings"><button className="btn btn--sm">Add OpenAI key</button></Link>
          )}
        </div>
      </div>

      <div
        className={"drop " + (dragOver ? "over" : "")}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        onDrop={(e) => { e.preventDefault(); setDragOver(false); handle(e.dataTransfer.files?.[0]); }}
        onClick={() => inputRef.current?.click()}
        style={{ cursor: "pointer" }}
      >
        <div style={{ fontSize: 22 }}>📄</div>
        <h3 style={{ margin: "6px 0" }}>Click to choose a PDF, or drop it here</h3>
        <p>Up to ~25 MB · text-based PDFs only (scanned images won't extract).</p>
        <input
          ref={inputRef}
          type="file"
          accept="application/pdf"
          style={{ display: "none" }}
          onChange={(e) => handle(e.target.files?.[0])}
        />
      </div>

      {busy && <div className="notice mt-16">{busyLabel || "Working…"}</div>}
      {error && <div className="notice notice--warn mt-16">{error}</div>}

      {draft && (
        <div className="card mt-16" style={{ display: "block" }}>
          <div className="spread">
            <h3 style={{ margin: 0 }}>
              Draft quiz · {draft.length} questions
              {draftSource && (
                <span className="tag" style={{ marginLeft: 10 }}>
                  {draftSource === "ai" ? "gpt-4o-mini" : "offline heuristic"}
                </span>
              )}
            </h3>
            <div className="row" style={{ gap: 8 }}>
              <input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Material / quiz title"
                style={{ background: "var(--bg-2)", color: "var(--text)", padding: "8px 10px", borderRadius: 10, border: "1px solid var(--border)" }}
              />
              <button className="btn btn--primary" onClick={save}>Save &amp; publish</button>
            </div>
          </div>

          <div className="mt-16">
            {draft.map((q, i) => (
              <div className="card mb-12" key={i} style={{ display: "block" }}>
                <div className="row"><span className="tag">Q{i + 1}</span></div>
                <p className="mt-12"><b>{q.q}</b></p>
                <ul className="list">
                  {q.opts.map((o, j) => (
                    <li className="list__item" key={j} style={j === q.a ? { borderColor: "rgba(42,157,143,0.6)", background: "rgba(42,157,143,0.08)" } : {}}>
                      <span>{String.fromCharCode(65 + j)}. {o}</span>
                      {j === q.a && <span className="tag">Correct</span>}
                    </li>
                  ))}
                </ul>
                <p className="muted" style={{ fontSize: 12 }}>{q.explain}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      <h3 className="section__title mt-24">Published materials</h3>
      {list.length === 0 && <div className="notice">No materials yet — upload your first PDF above.</div>}
      <div className="list">
        {list.map(m => (
          <div className="list__item" key={m.id}>
            <div>
              <div style={{ fontWeight: 700 }}>{m.title}</div>
              <div className="muted" style={{ fontSize: 12 }}>
                {new Date(m.when).toLocaleString()} · {m.by} · {m.generatedQuiz?.length || 0} questions
              </div>
            </div>
            <div className="row" style={{ gap: 8 }}>
              <Link to="/quiz" params={{ material: m.id }}><button className="btn btn--sm">Open quiz</button></Link>
              <button className="btn btn--sm btn--danger" onClick={() => remove(m.id)}>Delete</button>
            </div>
          </div>
        ))}
      </div>

      <div className="row mt-24">
        <button className="btn" onClick={() => navigate("/faculty")}>Back to dashboard</button>
      </div>
    </section>
  );
}
